### ISSUE TITLE
Is it using GPU?

### ISSUE THREAD

**Issue by glitchyordis** [ibaiGorordo/Tapir-Pytorch-Inference#2]
Hi, I tried to run the `example_video_tracking.py` on a Windows 11 laptop with GPU but I noticed my GPU is hardly utilized and inference was very slow. Am I missing something that will allow it to use GPU?

![image](https://github.com/user-attachments/assets/65e30007-0156-4ff6-b26f-57e444aa82ed)

**Comment by ibaiGorordo** [comment]
That will depend on your Pytorch installation, make sure you have the proper setup
